name: Deploy to Development
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - 'development'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VITE_API_BASE_URL: https://localhost:6030
          VITE_AUTH0_DOMAIN: dev-vxhscity7m14cski.us.auth0.com
          VITE_AUTH0_CLIENT_ID: sF0zfVTJUxtoI2gXBEmw0EU5dbmdvFEy
          VITE_AUTH0_CALLBACK_URL: https://mern-grub-dev.vercel.app
          VITE_AUTH0_AUDIENCE: MERN-Grub-Api
