name: Deploy to Vercel Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
        node-version: '20'

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel Production
        run: vercel --token ${{ secrets.VERCEL_TOKEN_PROD }} --prod
        env:
          VERCEL_TOKEN_PROD: ${{ secrets.VERCEL_TOKEN_PROD }}
          VERCEL_TOKEN_DEV: ${{ secrets.VERCEL_TOKEN_DEV }}
          PORT: ${{ secrets.PORT }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}

